<?php require __DIR__.'/common.php';
if($_SERVER['REQUEST_METHOD']==='GET') json_out(config());
require_auth(); if($_SERVER['REQUEST_METHOD']!=='POST') json_out(['error'=>'Method'],405);
$in=body(); $old=config();
$font=(string)($in['font_family']??$old['font_family']??'inter'); if(!in_array($font,['inter','system','serif','mono'],true))$font='inter';
$cfg=['name'=>substr((string)($in['name']??'Homelab'),0,80),'accent'=>preg_match('/^#[0-9a-f]{6}$/i',(string)($in['accent']??''))?$in['accent']:'#7c6af7','text_color'=>preg_match('/^#[0-9a-f]{6}$/i',(string)($in['text_color']??$old['text_color']??''))?($in['text_color']??$old['text_color']):'#ffffff','font_family'=>$font,'font_scale'=>max(50,min(200,(int)($in['font_scale']??$old['font_scale']??100))),'background'=>clean_rel((string)($in['background']??$old['background']??'backgrounds/default.svg')),'bg_random'=>array_key_exists('bg_random',$in)?(bool)$in['bg_random']:(bool)($old['bg_random']??false),'bg_rotation_minutes'=>max(0,(int)($in['bg_rotation_minutes']??$old['bg_rotation_minutes']??0)),'background_overlay'=>max(0,min(85,(int)($in['background_overlay']??$old['background_overlay']??40))),'video_loop'=>array_key_exists('video_loop',$in)?(bool)$in['video_loop']:(bool)($old['video_loop']??true),'video_muted'=>array_key_exists('video_muted',$in)?(bool)$in['video_muted']:(bool)($old['video_muted']??true),'weather'=>['city'=>substr((string)($in['weather']['city']??'Sibiu'),0,100),'latitude'=>(float)($in['weather']['latitude']??45.7983),'longitude'=>(float)($in['weather']['longitude']??24.1256),'units'=>($in['weather']['units']??'celsius')==='fahrenheit'?'fahrenheit':'celsius'],'status_interval'=>max(5,(int)($in['status_interval']??10)),'stats_interval'=>max(10,(int)($in['stats_interval']??30)),'disks'=>$old['disks']??['/'],'categories'=>[],'links'=>[],'hosts'=>[]];
foreach (($in['categories'] ?? []) as $category) { $category=substr(trim((string)$category),0,80); if ($category!==''&&!in_array($category,$cfg['categories'],true)) $cfg['categories'][]=$category; }
foreach(($in['links']??[]) as $cat){$items=[];foreach(($cat['items']??[]) as $it){$url=trim((string)($it['url']??''));if(!$url)continue;$items[]=['name'=>substr((string)($it['name']??'Link'),0,80),'url'=>$url,'icon'=>clean_rel((string)($it['icon']??'')),'desc'=>substr((string)($it['desc']??''),0,160)];}$cfg['links'][]=['category'=>substr((string)($cat['category']??'Other'),0,80),'items'=>$items];}
foreach ($cfg['links'] as $linkGroup) if ($linkGroup['category']!==''&&!in_array($linkGroup['category'],$cfg['categories'],true)) $cfg['categories'][]=$linkGroup['category'];
foreach(($in['hosts']??[]) as $h){$target=trim((string)($h['target']??''));if(!$target)continue;$paths=$h['metrics_paths']??preg_split('/[\r\n]+/',(string)($h['metrics_path']??$h['mount_path']??''));if(!is_array($paths))$paths=[];$paths=array_values(array_unique(array_filter(array_map(fn($path)=>substr(trim((string)$path),0,512),$paths),fn($path)=>$path!=='')));$cfg['hosts'][]=['name'=>substr((string)($h['name']??$target),0,80),'target'=>$target,'port'=>max(1,min(65535,(int)($h['port']??80))),'url'=>trim((string)($h['url']??'')),'metrics_url'=>trim((string)($h['metrics_url']??'')),'metrics_paths'=>array_slice($paths,0,10)];}
save_config($cfg);json_out(['ok'=>true]);